### ISSUE TITLE
Надати можливість через .env вказувати потрібний мені порт для веб додатку.

### ISSUE THREAD

**Issue by mdihtyar** [Alazzze/wordpress-docker-phpmyadmin#5]
https://github.com/Alazzze/wordpress-docker-phpmyadmin/blob/main/docker-compose.yml#L19C10-L19C10
Нараз там хардкод порта 8000, що заставляє мене змінювати код компоуз файлу для запуску на потрібному мені порті

**Comment by Alazzze** [comment]
Fixed
